server:
  port: 18800
spring:
  application:
    name: cloud-config-server
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    config:
      server:
        git:
          uri: https://github.com/ZongweiBai/springcloud-config
          searchPaths: '{application}'
#  security:
#    basic:
#      enabled: false
#    user:
#      name: root
#      password: booszy
  management:
    security:
      enabled: false
  endpoints:
    health:
      sensitive: false